import { useState } from 'react';
import ScoreGauge from '../components/ScoreGauge';
import DealSummary from '../components/DealSummary';
import MarketCheck from '../components/MarketCheck';
import FlagsPanel from '../components/FlagsPanel';
import FeeBreakdown from '../components/FeeBreakdown';
import NegotiationTips from '../components/NegotiationTips';

function buildEmailBody(result) {
  const v = result.vehicle || {};
  const e = result.entered || {};
  const c = result.calculated || {};
  const lines = [
    `BringTheApp - Deal Analysis Report`,
    ``,
    `SCORE: ${result.score}/100 — ${result.label}`,
    ``,
    `VEHICLE: ${v.year || ''} ${v.make || ''} ${v.model || ''} ${v.trim || ''}`.trim(),
    ``,
    `DEAL NUMBERS:`,
    e.price ? `  Vehicle Price: $${Number(e.price).toLocaleString()}` : null,
    e.msrp ? `  MSRP: $${Number(e.msrp).toLocaleString()}` : null,
    e.down ? `  Down Payment: $${Number(e.down).toLocaleString()}` : null,
    e.apr != null ? `  APR: ${e.apr}%` : null,
    e.term ? `  Term: ${e.term} months` : null,
    c.monthlyPayment ? `  Monthly Payment: $${Number(c.monthlyPayment).toFixed(2)}` : null,
    c.totalCost ? `  Total Cost: $${Number(c.totalCost).toLocaleString()}` : null,
    ``,
    result.flags?.redFlags?.length > 0 ? `RED FLAGS:` : null,
    ...(result.flags?.redFlags || []).map(f => `  ⚠ ${f}`),
    result.flags?.greenFlags?.length > 0 ? `GREEN FLAGS:` : null,
    ...(result.flags?.greenFlags || []).map(f => `  ✓ ${f}`),
    ``,
    `SCORE BREAKDOWN:`,
    ...(result.factors || []).map(f => `  ${f.name}: ${Math.max(0, f.points)}/${f.max}`),
    ``,
    `---`,
    `Generated by BringTheApp`,
  ].filter(l => l !== null);
  return lines.join('\n');
}

export default function ResultsView({ dealData, result, onEditDeal, onNewDeal }) {
  const [emailSent, setEmailSent] = useState(false);

  if (!result) return null;

  const handleEmail = () => {
    const v = result.vehicle || {};
    const subject = encodeURIComponent(`Deal Analysis: ${v.year || ''} ${v.make || ''} ${v.model || ''} — ${result.score}/100`.trim());
    const body = encodeURIComponent(buildEmailBody(result));
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    setEmailSent(true);
    setTimeout(() => setEmailSent(false), 3000);
  };

  return (
    <div className="stagger space-y-4 pb-8">
      {/* Panel 1: Score */}
      <ScoreGauge
        score={result.score}
        label={result.label}
        vehicle={result.vehicle}
      />

      {/* Panel 2: Deal Summary */}
      <DealSummary
        entered={result.entered}
        calculated={result.calculated}
      />

      {/* Panel 3: Market Check */}
      <MarketCheck
        vehicle={result.vehicle}
        market={result.market}
        price={result.entered.price}
      />

      {/* Panel 4: Flags */}
      <FlagsPanel
        redFlags={result.flags.redFlags}
        greenFlags={result.flags.greenFlags}
      />

      {/* Panel 5: Fee Breakdown */}
      <FeeBreakdown
        calculated={result.calculated}
        entered={result.entered}
      />

      {/* Negotiation Scripts */}
      <NegotiationTips scripts={result.scripts} />

      {/* Scoring Factors Breakdown */}
      <div className="bg-surface border border-border rounded-xl overflow-hidden">
        <div className="p-4 border-b border-border">
          <h3 className="font-semibold text-text">Score Breakdown</h3>
        </div>
        <div className="p-4 space-y-2">
          {result.factors.map((f, i) => {
            const displayPoints = Math.max(0, f.points);
            const pct = f.max > 0 ? (displayPoints / f.max) * 100 : 0;
            const barColor = displayPoints === 0 ? 'var(--color-red)' : displayPoints >= f.max * 0.7 ? 'var(--color-green)' : 'var(--color-amber)';
            return (
              <div key={i} className="flex items-center gap-3">
                <div className="flex-1">
                  <div className="flex justify-between text-sm mb-1">
                    <span className="text-text">{f.name}</span>
                    <span className={`font-medium ${displayPoints === 0 ? 'text-red' : displayPoints >= f.max * 0.7 ? 'text-green' : 'text-amber'}`}>
                      {displayPoints}/{f.max}
                    </span>
                  </div>
                  <div className="h-1.5 bg-surface2 rounded-full overflow-hidden">
                    <div
                      className="h-full rounded-full transition-all duration-500"
                      style={{
                        width: `${Math.max(0, pct)}%`,
                        backgroundColor: barColor,
                      }}
                    />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Email Results */}
      <button
        onClick={handleEmail}
        className="w-full py-3.5 bg-surface border border-border text-text font-semibold rounded-xl hover:bg-surface2 transition-colors flex items-center justify-center gap-2"
      >
        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
        </svg>
        {emailSent ? 'Opening email app...' : 'Email This Report'}
      </button>

      {/* Action Buttons */}
      <div className="flex gap-3">
        <button
          onClick={onEditDeal}
          className="flex-1 py-3 bg-surface border border-border text-text font-semibold rounded-xl hover:bg-surface2 transition-colors"
        >
          Edit Deal
        </button>
        <button
          onClick={onNewDeal}
          className="flex-1 py-3 bg-accent hover:bg-accent-hover text-white font-semibold rounded-xl transition-colors"
        >
          New Deal
        </button>
      </div>
    </div>
  );
}
