import { Resend } from 'resend';
import { buildDealPdfBuffer } from '../routes/pdf.js';
import type { DealAnalysisResponse } from '../../shared/types.js';

/**
 * Email a deal analysis PDF to a recipient as an attachment, via Resend.
 * Requires RESEND_API_KEY and EMAIL_FROM env vars; throws clear errors if unset.
 */
export async function sendReportEmail({ to, result }: { to: string; result: DealAnalysisResponse }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.EMAIL_FROM;
  if (!apiKey) throw new Error('RESEND_API_KEY is not configured');
  if (!from) throw new Error('EMAIL_FROM is not configured');

  const { buffer, filename } = await buildDealPdfBuffer(result);

  const v = result.vehicle || {};
  const score = Number(result.score) || 0;
  const vehicle = [v.year, v.make, v.model].filter(Boolean).join(' ') || 'your vehicle';
  const subject = `Your BringTheApp deal report — ${vehicle} (${score}/100)`;

  const resend = new Resend(apiKey);
  const { error } = await resend.emails.send({
    from,
    to,
    subject,
    html: `
      <div style="font-family: Arial, Helvetica, sans-serif; color: #0f172a; line-height: 1.6;">
        <h2 style="margin: 0 0 8px;">Your deal report is ready</h2>
        <p style="margin: 0 0 4px;"><strong>${vehicle}</strong></p>
        <p style="margin: 0 0 16px;">Deal score: <strong>${score}/100</strong>${result.label ? ` — ${result.label}` : ''}</p>
        <p style="margin: 0 0 16px;">Your full analysis is attached as a PDF. Bring it to the dealership so you know exactly where you stand before you sign.</p>
        <p style="color: #64748b; font-size: 12px; margin: 24px 0 0;">Generated by BringTheApp · bringtheapp.onrender.com · For informational purposes only.</p>
      </div>
    `,
    attachments: [{ filename, content: buffer }],
  });

  if (error) throw new Error(error.message || 'Resend failed to send the email');
}
